services:
  db:
   image: postgres:16
   container_name: postgres-db
   restart: unless-stopped
   environment:
     POSTGRES_DB: ingestion
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   ports:
   - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data


  app:
   build: .
   container_name: world-monitor-app
   ports:
   - "8001:8001"
   depends_on:
   - db
   environment:
     DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/ingestion
   env_file:
    - .env
  
  monitoring:
   image: prom/prometheus:latest
   container_name: Prometheus-Monitoring
   ports: 
   - "9090:9090"
   volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
   command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'



volumes:
  postgres_data:
  prometheus_data:    
